<!DOCTYPE html>
<html lang="en-us">
  <head>
    <meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="generator" content="Hugo 0.104.3" />


<title>CFB Recruiting Rankings and Analysis - Shane Connuck&#39;s Site</title>
<meta property="og:title" content="CFB Recruiting Rankings and Analysis - Shane Connuck&#39;s Site">


  <link href='https://sconnuck.github.io/favicon.ico' rel='icon' type='image/x-icon'/>



  








<link href='//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/styles/github.min.css' rel='stylesheet' type='text/css' />



<link rel="stylesheet" href="/css/fonts.css" media="all">
<link rel="stylesheet" href="/css/main.css" media="all">



  </head>
  <body>
    <div class="wrapper">
      <header class="header">
        <nav class="nav">
  <a href="/" class="nav-logo">
    <img src="/images/logo.png"
         width="50"
         height="50"
         alt="Logo">
  </a>

  <ul class="nav-links">
    
    <li><a href="/about/">About</a></li>
    
    <li><a href="https://github.com/sconnuck">GitHub</a></li>
    
    <li><a href="https://twitter.com/rstudio">Twitter</a></li>
    
  </ul>
</nav>

      </header>


<main class="content" role="main">

  <article class="article">
    
    <span class="article-duration">4 min read</span>
    

    <h1 class="article-title">CFB Recruiting Rankings and Analysis</h1>

    
    <span class="article-date">2022-10-20</span>
    

    <div class="article-content">
      


<p>Every offseason, coaches at the highest levels of college athletics set out to build the best team they can. While coaches in college football, for example, are only manning the sidelines 12 or 13 times each year during games, they are recruiting the top high school talent and biggest names in the transfer portal all year long.</p>
<p>Recruiting often translates to success. If you bring in better players, you should have a better team. But how often is that actually the case? Let’s take a look at how it’s gone in college football.</p>
<pre class="r"><code>library(tidyverse)</code></pre>
<pre><code>## ── Attaching packages ─────────────────────────────────────── tidyverse 1.3.2 ──
## ✔ ggplot2 3.3.6     ✔ purrr   0.3.5
## ✔ tibble  3.1.8     ✔ dplyr   1.0.9
## ✔ tidyr   1.2.0     ✔ stringr 1.4.1
## ✔ readr   2.1.2     ✔ forcats 0.5.2
## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
## ✖ dplyr::filter() masks stats::filter()
## ✖ dplyr::lag()    masks stats::lag()</code></pre>
<pre class="r"><code>all_teams &lt;- read_csv(&quot;https://dwillis.github.io/sports-data-files/all_teams.csv&quot;)</code></pre>
<pre><code>## Rows: 904 Columns: 21
## ── Column specification ────────────────────────────────────────────────────────
## Delimiter: &quot;,&quot;
## chr  (3): team, conference, division
## dbl (18): year, expected_wins, total_games, total_wins, total_losses, total_...
## 
## ℹ Use `spec()` to retrieve the full column specification for this data.
## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
<pre class="r"><code>recruiting &lt;- read_csv(&quot;https://dwillis.github.io/sports-data-files/all_rankings.csv&quot;)</code></pre>
<pre><code>## Rows: 400 Columns: 3
## ── Column specification ────────────────────────────────────────────────────────
## Delimiter: &quot;,&quot;
## chr (1): team
## dbl (2): rating, year
## 
## ℹ Use `spec()` to retrieve the full column specification for this data.
## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
<pre class="r"><code>combined &lt;- all_teams %&gt;% inner_join(recruiting, by=c(&quot;team&quot;, &quot;year&quot;))</code></pre>
<pre class="r"><code>ggplot() + geom_point(data=combined, aes(x=total_wins, y=rating))</code></pre>
<p><img src="https://sconnuck.github.io/2022/10/20/cfb-recruiting-rankings-and-analysis/index_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<pre class="r"><code>ggplot() + 
  geom_point(data=combined, aes(x=total_wins, y=rating)) +
  geom_smooth(data=combined, aes(x=total_wins, y=rating), method=&quot;lm&quot;)</code></pre>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<p><img src="https://sconnuck.github.io/2022/10/20/cfb-recruiting-rankings-and-analysis/index_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<pre class="r"><code>fit &lt;- lm(rating ~ total_wins, data = combined)
summary(fit)</code></pre>
<pre><code>## 
## Call:
## lm(formula = rating ~ total_wins, data = combined)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -64.446 -27.525  -6.753  26.029  80.762 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 196.0666     4.9784  39.384  &lt; 2e-16 ***
## total_wins    4.5415     0.6152   7.382 1.16e-12 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 34.64 on 348 degrees of freedom
## Multiple R-squared:  0.1354, Adjusted R-squared:  0.1329 
## F-statistic: 54.49 on 1 and 348 DF,  p-value: 1.161e-12</code></pre>
<pre class="r"><code>umd &lt;- combined %&gt;% filter(team == &quot;Maryland&quot;)</code></pre>
<pre class="r"><code>ggplot() + 
  geom_point(data=combined, aes(x=total_wins, y=rating)) +
  geom_smooth(data=combined, aes(x=total_wins, y=rating), method=&quot;lm&quot;) +
  geom_point(data=umd, aes(x=total_wins, y=rating), color=&quot;red&quot;)</code></pre>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<p><img src="https://sconnuck.github.io/2022/10/20/cfb-recruiting-rankings-and-analysis/index_files/figure-html/unnamed-chunk-9-1.png" width="672" />
There’s an adjusted R squared value of 0.1329, which means that only about 13 percent of a team’s wins are as a result of its recruiting, according to 247 Sports’ recruiting ratings.</p>
<p>Let’s see how many of Maryland’s wins came as a result of said rating.</p>
<pre class="r"><code>fit &lt;- lm(rating ~ total_wins, data = umd)
summary(fit)</code></pre>
<pre><code>## 
## Call:
## lm(formula = rating ~ total_wins, data = umd)
## 
## Residuals:
##       1       2       3       4       5       6       7 
##  11.428  11.534 -10.076   7.806  23.775 -24.523 -19.946 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  189.838     20.814   9.121 0.000265 ***
## total_wins     4.139      4.527   0.914 0.402466    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 19.95 on 5 degrees of freedom
## Multiple R-squared:  0.1433, Adjusted R-squared:  -0.02809 
## F-statistic: 0.8361 on 1 and 5 DF,  p-value: 0.4025</code></pre>
<p>With an adjusted R-squared of -0.02809, this means that Maryland’s wins were not as a result of its recuriting class. This makes sense, as the Terrapins hadn’t been particularly strong in recruiting and seemed to have overachieved a bit.</p>
<p>Still, it’s tough to tell just how conclusive these ratings are. But it remains true that a team recruiting better could only help them win more games.</p>

    </div>
  </article>

  


</main>

      <footer class="footer">
        <ul class="footer-links">
          <li>
            <a href="/index.xml" type="application/rss+xml" target="_blank">RSS feed</a>
          </li>
          <li>
            <a href="https://gohugo.io/" class="footer-links-kudos">Made with <img src="/images/hugo-logo.png" alt="Img link to Hugo website" width="22" height="22"></a>
          </li>
        </ul>
      </footer>

    </div>
    



<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js"></script>



<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/languages/r.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/languages/yaml.min.js"></script>
<script>hljs.configure({languages: []}); hljs.initHighlightingOnLoad();</script>



    

    
  </body>
</html>

